<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Revenue Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #222;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .logo {
            width: 80px;
            margin-bottom: 10px;
        }

        .title {
            font-size: 22px;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .subtitle {
            font-size: 14px;
            color: #555;
            margin-bottom: 15px;
        }

        .summary-table,
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        .summary-table th,
        .summary-table td,
        .data-table th,
        .data-table td {
            border: 1px solid #bbb;
            padding: 8px;
            text-align: left;
        }

        .summary-table th {
            background: #f0f0f0;
        }

        .data-table th {
            background: #e0e7ef;
        }

        .section-title {
            font-size: 16px;
            font-weight: bold;
            margin: 18px 0 8px 0;
        }

        .footer {
            text-align: center;
            font-size: 10px;
            color: #888;
            margin-top: 30px;
        }
    </style>
</head>

<body>
    <div class="header">
        <!-- Optional: Add your logo here -->
        <!-- <img src="assets/images/logo.png" class="logo"> -->
        <div class="title">Revenue Report</div>
        <div class="subtitle">Period: <?= htmlspecialchars($startDate) ?> to <?= htmlspecialchars($endDate) ?></div>
    </div>

    <table class="summary-table">
        <tr>
            <th>Total Revenue</th>
            <th>Total Rentals</th>
            <th>Average Rental Value</th>
        </tr>
        <tr>
            <td>RWF <?= number_format($totals['total_revenue'], 2) ?></td>
            <td><?= $totals['total_rentals'] ?></td>
            <td>RWF <?= number_format($totals['average_rental'], 2) ?></td>
        </tr>
    </table>

    <div class="section-title">Revenue by Category</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Category</th>
                <th>Revenue</th>
                <th>Rentals</th>
                <th>Average Value</th>
                <th>% of Total</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categoryData as $category): ?>
                <tr>
                    <td><?= htmlspecialchars($category['category']) ?></td>
                    <td>RWF <?= number_format($category['revenue'], 2) ?></td>
                    <td><?= $category['rentals'] ?></td>
                    <td>RWF <?= number_format($category['revenue'] / $category['rentals'], 2) ?></td>
                    <td><?= number_format(($category['revenue'] / $totals['total_revenue']) * 100, 1) ?>%</td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="section-title">Daily Revenue Data</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Revenue</th>
                <th>Rentals</th>
                <th>Average Value</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($revenueData as $data): ?>
                <tr>
                    <td><?= date('M d, Y', strtotime($data['date'])) ?></td>
                    <td>RWF <?= number_format($data['daily_revenue'], 2) ?></td>
                    <td><?= $data['rental_count'] ?></td>
                    <td>RWF <?= number_format($data['daily_revenue'] / $data['rental_count'], 2) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="footer">
        Generated by AI-Enhanced Smarter Car Rental Management System | <?= date('Y-m-d H:i') ?>
    </div>
</body>

</html>